# This is a basic workflow to help you get started with Actions

name: Build in CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.0.0

    - name: Run Unit Tests
      run: ./test.sh

    - name: Install MiniCore
      run: |
        sudo apt update
        sudo apt install gcc-avr binutils-avr avr-libc
        arduino-cli core update-index --additional-urls https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json
        arduino-cli core install MiniCore:avr --additional-urls https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json
        sed -i 's~{runtime.tools.avr-gcc.path}~/usr~g' ~/.arduino*/packages/MiniCore/hardware/avr/*/platform.txt

    - name: Run the build
      run: ./build.sh
